---
- name: create ssl_exporter system group
  group:
    name: ssl-exp
    system: true
    state: present

- name: create ssl_exporter system user
  user:
    name: ssl-exp
    system: true
    shell: "/sbin/nologin"
    group: ssl-exp
    createhome: false

- name: download ssl exporter binary to local folder
  become: false
  unarchive:
    src: "https://github.com/ribbybibby/ssl_exporter/releases/download/v{{ ssl_exporter_version }}/ssl_exporter_{{ ssl_exporter_version }}_linux_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/ssl_exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: propagate ssl exporter binary
  copy:
    src: "/tmp/ssl_exporter"
    dest: "/usr/local/bin/ssl_exporter"
    mode: 0750
    owner: ssl-exp
    group: ssl-exp
  notify:
    - restart ssl exporter

- name: Install libcap on Debian systems
  package:
    name: "libcap2-bin"
    state: present
  register: _download_packages
  until: _download_packages is succeeded
  retries: 5
  delay: 2
  when: ansible_os_family | lower == "debian"

- name: Ensure ssl exporter binary has cap_net_raw capability
  capabilities:
    path: '/usr/local/bin/ssl_exporter'
    capability: cap_net_raw+ep
    state: present
