---
- include: preflight.yml
  tags:
    - ssl_exporter_install
    - ssl_exporter_configure
    - ssl_exporter_run

- include: install.yml
  become: true
  tags:
    - ssl_exporter_install

- include: configure.yml
  become: true
  tags:
    - ssl_exporter_configure

- name: ensure ssl_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: ssl_exporter
    state: started
    enabled: true
  tags:
    - ssl_exporter_run
