---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    ssl_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in ssl_exporter_web_listen_address"

- name: Update latest release tag
  check_mode: false
  block:
    - name: Get github release info
      uri:
        url: "https://api.github.com/repos/{{ ssl_exporter_repo }}/releases/latest"
        return_content: true
      register: json_reponse
    - name: Export latest release
      set_fact:
        ssl_exporter_version: "{{ json_reponse.json.tag_name | regex_replace('^v','') }}"
  when: ssl_exporter_version == 'latest'
